### PR TITLE
Fix linkage issue and TEMP0001.XXX garbage file issue

### PR DESCRIPTION
**Pull request by MengZhang**
---
name: Pull Request
about: Fill out this template before submitting a Pull Request.
title: Pull Request
labels: 'pull request'
assignees: ''
---

## Checklist:

- [ ] I have read the documentation on [CONTRIBUTING](https://github.com/AgPipeline/Organization-info) 
- [ ] My updates require a change to the documentation 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
Hi @MengZhang, thanks again for helping us troubleshoot this. It looks like this pull request includes a slightly modified version of the data file, and the only error in the linkage file was a new line at the end? 

I think this fixes the IPPLNT error we were having! And the more general problem with the DOME not being read, because I'm now getting files with the extension .SGX instead of .XXX. 

---

I ran the two files in this pull request along with [David's DOME](https://github.com/cct-datascience/ardn-terra-ref/pull/5/files#diff-9a7ee7e81bb5e2a2b59895f95b5d400402891a081124ad5b1ae6e8c361a1d6cf) through the browser version of QuadUI to get DSSAT input files. I then ran `/Users/kristinariemer/Dropbox/Documents/UofA/Projects/ARDN/DSSAT_compiled/dscsm048 b DSSBatch.v47`, where the first path is to the compiled version of DSSAT on my machine. I got the below error, which we've seen before and I think has been fixed by manually changing the TERRA01.SGX file? Or should the DOME file be modified? 

```
 Start simulation date or planting date missing. Correct input file.
File: TERRAR01   Line:    82   Error key: MAKEFW

Additional information may be available in WARNING.OUT file.


 Please press < ENTER > key to continue STOP 99
```
It looks like [the line](https://github.com/cct-datascience/ardn-terra-ref/blob/d40e39e6d910440a9da1997cce7c4068b9190e7e/dssat/Field_Overlay_s4.csv#L121) in the DOME relevant to this error is not being included with a `&`? 

---

Okay, I added that line in the dome. Now I'm getting a missing weather file, which might have something to do with where and how DSSAT is compiled on my machine? Or should that file be generated by [this DOME line](https://github.com/cct-datascience/ardn-terra-ref/blob/d40e39e6d910440a9da1997cce7c4068b9190e7e/dssat/Field_Overlay_s4.csv#L126)? 

```
 Weather file not found.  Please check file name or create file.
File: AAAA1801.WTH   Line:     0   Error key: MAKEFW

Additional information may be available in WARNING.OUT file.


 Please press < ENTER > key to continue STOP 99
```

**Comment by dlebauer** [comment]
Is there a reason to replace the file with one named _v2.csv, or can we just update the original linkage file? I think the only difference is that there was a leading whitespace on line 1 in LINKAGE_s4.csv that I have since removed.

**Comment by KristinaRiemer** [comment]
Adding two new virtual columns for weather and soil data to the studies table from within the Vmapper: 
Screen Shot 2022-06-08 at 8 11 35 AM

**Comment by dlebauer** [comment]
Thanks for your feedback - @KristinaRiemer has fixed this in another branch

**Pull request closed without merging**
